# Introduction to Scikit-learn

This notebook demonstrates some of the most beautiful functions of the beautiful Scikit-learn library.

What we'll cover.

0.  An end-to-end Scikit-learn workflow.
1.  Getting the Data ready.
2.  Choose the right estimator/algorithm/model for our problems.
3.  Fit the model algorithm/model and use it to make predictions on our data.
4.  Evaluating a model.
5.  Improve a model.
6.  Save and load a trained model.
7.  Putting it all together!

## 0.  An end-to-end Scikit-learn workflow.

---
## 1. Get the data ready

### Standard Imports

In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [99]:
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1     37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2     41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3     56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4     57    0   0       120   354    0        1      163      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0        1      123      1      0.2      1   0     3       0
299   45    1   3       110   264    0        1      132      0      1.2      1   0     3       0
300   68    1   0       144   193    1        1      141      0      3.4      1   2     3       0
301   57    1   0       130   131    0        1      115      1      1.2      1   1     3       0
302   57    0   1       130   236    0        0      174      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [100]:
#  Create X (features matrix)
X = heart_disease.drop("target", axis=1)

#  Create y (labels)
y = heart_disease["target"]

### to filter warnings
- default/ignore

In [101]:
# import warnings
# warnings.filterwarnings("default")

---
## 2. Choose the right model and hyperparameters.

### RandomForestClassifier
- A random forest classifier.
- A random forest is a meta estimator that fits a number of decision tree
classifiers on various sub-samples of the dataset and uses averaging to
improve the predictive accuracy and control over-fitting.

### get_params()
- Get parameters for this estimator.

In [102]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

---
### 3. Fit the model to the training data and use it to make predictions.

### train_test_split
- Split arrays or matrices into random train and test subsets.

### fit
- Build a forest of trees from the training set (X, y).

In [103]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [104]:
clf.fit(X_train , y_train);

### Make Predictions.

In [105]:
# y_label = clf.predict(np.array([0, 2, 3, 4]));

In [106]:
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [107]:
y_test

179    0
228    0
111    1
246    0
60     1
      ..
249    0
104    1
300    0
193    0
184    0
Name: target, Length: 61, dtype: int64

## 4. Evaluate the model on the training data and test data.

### score
- Return the mean accuracy on the provided data and labels.

In [108]:
clf.score(X_train, y_train)

1.0

In [109]:
clf.score(X_test, y_test)

0.8524590163934426

### classification_report
- Build a text report showing the main classification metrics.
### confusion_matrix
- Compute confusion matrix to evaluate the accuracy of a classification.
### accuracy_score
- Accuracy classification score, In multilabel classification, this function computes subset accuracy:
the set of labels predicted for a sample must *exactly* match the
corresponding set of labels in y_true.

In [110]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.86      0.83      0.84        29
           1       0.85      0.88      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

In [111]:
confusion_matrix(y_test, y_preds)

array([[24,  5],
       [ 4, 28]])

In [112]:
accuracy_score(y_test, y_preds)

0.8524590163934426

## 5. Improve a model.

### Try different amount of n_estimators

In [113]:
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")

Trying model with 10 estimators...
Model accuracy on test set: 85.25%
Trying model with 20 estimators...
Model accuracy on test set: 80.33%
Trying model with 30 estimators...
Model accuracy on test set: 83.61%
Trying model with 40 estimators...
Model accuracy on test set: 80.33%
Trying model with 50 estimators...
Model accuracy on test set: 86.89%
Trying model with 60 estimators...
Model accuracy on test set: 83.61%
Trying model with 70 estimators...
Model accuracy on test set: 83.61%
Trying model with 80 estimators...
Model accuracy on test set: 83.61%
Trying model with 90 estimators...
Model accuracy on test set: 81.97%

## 6. Save a Model and Load it.

In [114]:
import pickle

with open("random_forest_model_1.pkl", "wb") as f:
    pickle.dump(clf, f)

In [115]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(X_test, y_test)

0.819672131147541

---
### Let's get start one by one.
# 1. Getting our data ready to be used with Machine Learning.
 Three main things we have to do.
   1. Split the data into features and labels (usually `X` & `y`)
   2. Filling (also called imputing) or disregarding missing values
   3. Converting non-numercial values to numerical-values (also called feature encoding)

In [116]:
heart_disease.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1   37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2   41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3   56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4   57    0   0       120   354    0        1      163      1      0.6      2   0     2       1

In [117]:
X = heart_disease.drop("target", axis=1)
X.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal
0   63    1   3       145   233    1        0      150      0      2.3      0   0     1
1   37    1   2       130   250    0        1      187      0      3.5      0   0     2
2   41    0   1       130   204    0        0      172      0      1.4      2   0     2
3   56    1   1       120   236    0        1      178      0      0.8      2   0     2
4   57    0   0       120   354    0        1      163      1      0.6      2   0     2

In [118]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### Split the data into training and testing set.

In [119]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2)

In [120]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

### 1.1 Make sure it's all numerical

In [121]:
car_sales = pd.read_csv("data/car-sales-extended.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [122]:
len(car_sales)

1000

In [123]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

### Split into X/y

In [124]:
X = car_sales.drop(["Price"], axis=1)
y = car_sales["Price"]

### Spliting into training and testing data set.

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

### Build Machine Learning Model

In [126]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Toyota'

### 1.1 Turn the categories into numbers.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)],
                               remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

### One more way to do

In [ ]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

### Let's refit our Model.

In [ ]:
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)
model.fit(X_train, y_train)

In [ ]:
model.score(transformed_X, y)

---
### 1.2 What if there were missing values ?

1. Fill them with some value (also known as imputation).
2. Remove the samples with missing data altogether.

In [ ]:
# import car sales missing data
car_sales_missing_data = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sales_missing_data.head()

In [ ]:
car_sales_missing_data.isna().sum()

###  Create X & y

In [ ]:
X = car_sales_missing_data.drop("Price", axis=1)
y = car_sales_missing_data["Price"]

In [ ]:
# Convert data To Numbers
# Turn the categories into numbers.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)],
                               remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

### Option 1 : Fill missing data with Pandas.

In [ ]:
# Fill the "Make" Cloumn
# car_sales_missing_data["Make"].fillna("missing", inplace=True)
car_sales_missing_data.fillna({"Make": "missing"}, inplace=True)

# Fill the "Colour" Column
# car_sales_missing_data["Colour"].fillna("missing", inplace=True)
car_sales_missing_data.fillna({"Colour": "missing"}, inplace=True)

# Fill the "Odometer (KM)" Column
# car_sales_missing_data["Odometer (KM)"].fillna(car_sales_missing_data["Odometer (KM)"].mean(), inplace=True)
car_sales_missing_data.fillna({"Odometer (KM)": car_sales_missing_data["Odometer (KM)"].mean()}, inplace=True)

# Fill the "Doors" Column
car_sales_missing_data.fillna({"Doors": 4}, inplace=True)

In [ ]:
# Check our DataFrame again
car_sales_missing_data.isna().sum()

In [ ]:
#  Remove row with missing "Price" values
car_sales_missing_data.dropna(inplace=True)

In [ ]:
car_sales_missing_data.isna().sum()

In [ ]:
len(car_sales_missing_data)

In [ ]:
X = car_sales_missing_data.drop(["Price"], axis=1)
y = car_sales_missing_data["Price"]

### Convert data To Numbers
### Turn the categories into numbers.

In [ ]:
# Convert data To Numbers
# Turn the categories into numbers.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)],
                               remainder="passthrough")

transformed_X = transformer.fit_transform(car_sales_missing_data)
transformed_X

### Option 2 : Fill missing data with Scikit-learn.

In [ ]:
car_sales_missing = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sales_missing.head()

In [ ]:
car_sales_missing.isna().sum()

###  Drop the row with no labels.

In [ ]:
car_sales_missing.dropna(subset=["Price"], inplace=True) # drop the row where Price value is missing
car_sales_missing.isna().sum()

### Split into X and y

In [ ]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

### Fill missing values(Imputation) with Scikit-learn.

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with "missing" & numerical values with mean.
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Define columns
cat_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# Create an imputer (somethings that fills missing data)
imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer, door_features),
    ("num_imputer", num_imputer, num_features)
])

# Transform the data
filled_X = imputer.fit_transform(X)
filled_X

In [ ]:
car_sales_filled = pd.DataFrame(filled_X, columns=["Make", "Colour", "Doors", "Odometer (KM)"])
car_sales_filled.head()

In [ ]:
car_sales_filled.isna().sum()

In [ ]:
# Convert data To Numbers
# Turn the categories into numbers.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)],
                               remainder="passthrough")

transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

### Now we got our data as numbers and filled missing values.
### Let's fit a Model

In [ ]:
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

---
# 2. Choosing the right estimator/algorithm for our problem.

### Scikit-learn uses estimators as another term of machine learning model or algorithm.
* Classification - predicting whether a sample is one thing or another.
* Regression - predicting a number.

Step-1 : Check the ML Mindmap. (https://scikit-learn.org/stable/machine_learning_map.html)

---
## ML MINDMAP FOR MODEL SELECTION
- Condition - Blue
- ML Model - Green
![ML Mind Map](data/ml_map.svg)

---
### 2.1 Picking a ML Model for Regression Problem

In [ ]:
import pandas as pd
import numpy as np

# Load Boston Housing dataset from original source
url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(url, sep=r"\s+", skiprows=22, header=None)

# Reconstruct feature matrix (same as sklearn load_boston)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])

# Reconstruct target vector
target = raw_df.values[1::2, 2]

# Feature names (same order as sklearn)
feature_names = [
    "CRIM","ZN","INDUS","CHAS","NOX","RM","AGE","DIS",
    "RAD","TAX","PTRATIO","B","LSTAT"
]

# Create dictionary similar to load_boston()
boston = {
    "data": data,
    "feature_names": feature_names,
    "target": target
}

# Create DataFrame exactly like old tutorial
boston_df = pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"] = pd.Series(boston["target"])

# Preview
boston_df.head()

In [ ]:
# How many samples?
len(boston_df)

In [ ]:
boston_df.info()

### Let's try the Ridge Regression Model

In [ ]:
from sklearn.linear_model import Ridge

# Setup random seed
np.random.seed(42)

# Create the data
X = boston_df.drop("target", axis=1)
Y = boston_df["target"]

# Split into train and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Instantiate Ridge Model
model = Ridge()
model.fit(X_train, Y_train)

# Check the score of ridge model on test data
model.score(X_test, Y_test)

### How do we improve our Score ?
### What if Ridge wasn't working ?

### Let's try Random Forest Regressor.

In [127]:
from sklearn.ensemble import RandomForestRegressor

# Setup random seed
np.random.seed(42)

# Create the data
X = boston_df.drop("target", axis=1)
Y = boston_df["target"]

# Split into train and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Instantiate Ridge Model
rf_model = RandomForestRegressor()
rf_model.fit(X_train, Y_train)

# Check the score of ridge model on test data
rf_model.score(X_test, Y_test)

0.8654448653350507

---
### 2.2 Choosing an Estimator / Ml Model for Classification Problem.
(Refer ML-Mindmap)

In [128]:
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1   37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2   41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3   56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4   57    0   0       120   354    0        1      163      1      0.6      2   0     2       1

In [129]:
len(heart_disease)

303

While Consulting the ML-Mindmap it says to try `LinearSVC`

In [136]:
from sklearn.svm import LinearSVC

# Setup random seed
np.random.seed(42)

# Create the data
X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

# Split into train and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Instantiate Linear SVC Model
LSVC_model = LinearSVC()
LSVC_model.fit(X_train, Y_train)

# Check the score of Linear_SVC model on test data
LSVC_model.score(X_test, Y_test)

0.8688524590163934

In [134]:
heart_disease["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [137]:
# Import RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Create the data
X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

# Split into train and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Instantiate Random Forest Classifier
rfc_model = RandomForestClassifier()
rfc_model.fit(X_train, Y_train)

# Evaluate the Random Forest Classifier
rfc_model.score(X_test, Y_test)

0.8524590163934426

### Note:

1. If you have structured data, use ensemble methods.
2. If you have unstructured data, use deep learning or transfer learning.

In [139]:
heart_disease

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1     37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2     41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3     56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4     57    0   0       120   354    0        1      163      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0        1      123      1      0.2      1   0     3       0
299   45    1   3       110   264    0        1      132      0      1.2      1   0     3       0
300   68    1   0       144   193    1        1      141      0      3.4      1   2     3       0
301   57    1   0       130   131    0        1      115      1      1.2      1   1     3       0
302   57    0   1       130   236    0        0      174      0      0.0      1   1     2       0

[303 rows x 14 columns]